### ISSUE TITLE
Very Minor error on typing for `pyspark-iris`

### ISSUE THREAD

**Issue by GabrielAzevedoFerreiraQB** [quantumblacklabs/kedro-starters#21]
`pyspark-iris/{{ cookiecutter.repo_name }}/src/{{ cookiecutter.python_package }}/pipelines/data_engineering/nodes.py`
**line 72 should be `List[DataFrame]`** (it seems to me, unless I read the output of randomSplit wrong)

![image](https://user-images.githubusercontent.com/57528979/108586997-5beff400-738c-11eb-80fa-60a1bdb6ae0b.png)

I'd raise this small PR myself, but only have read access

**Comment by lorenabalan** [comment]
Hey @GabrielAzevedoFerreiraQB thanks for raising, we'll address it on our side. 

> I'd raise this small PR myself, but only have read access

That's odd, I'll dig into this.

**Comment by AntonyMilneQB** [comment]
Thanks for pointing this out! I have implement it in https://github.com/quantumblacklabs/private-kedro/pull/1002.
